version: '3.8'

services:
  # Streamlit Application
  streamlit-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sp500-prediction-app
    ports:
      - "8501:8501"
    volumes:
      # Mount source code for development (remove in production)
      - ./src:/app/src:ro
      # Data persistence
      - app-data:/app/data
      # Logs
      - app-logs:/app/logs
    environment:
      - PYTHONPATH=/app
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - app-network

  # Optional: Redis for session storage (future enhancement)
  # redis:
  #   image: redis:7-alpine
  #   container_name: sp500-redis
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis-data:/data
  #   restart: unless-stopped
  #   networks:
  #     - app-network

volumes:
  app-data:
    driver: local
  app-logs:
    driver: local
  # redis-data:
  #   driver: local

networks:
  app-network:
    driver: bridge
